adding failsafe for tests to toggle build fail

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -124,7 +124,14 @@ stages:
           export public_key=$(cat id_rsa.pub)
           find $(modulePath)/cluster/environments/azure-simple -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
           go test -v -run TestIT_Bedrock_AzureSimple_Test -timeout 99999s | tee TestIT_Bedrock_AzureSimple_Test.log
+          failed=$?
           terratest_log_parser -testlog TestIT_Bedrock_AzureSimple_Test.log -outputdir single_test_output
+          if [ $failed -eq 0 ]
+          then
+            echo "Bedrock_Build_Azure_Simple: Test passed."
+          else
+            echo "Bedrock_Build_Azure_Simple: Test failed."
+            exit 1
         env:
           ARM_CLIENT_ID: $(ARM_CLIENT_ID)
           ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
@@ -175,7 +182,14 @@ stages:
         export public_key=$(cat id_rsa.pub)
         find $(modulePath)/cluster/environments/azure-single-keyvault -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
         go test -v -run TestIT_Bedrock_AzureCommon_KV_Test -timeout 99999s | tee TestIT_Bedrock_AzureCommon_KV_Test.log
+        failed=$?
         terratest_log_parser -testlog TestIT_Bedrock_AzureCommon_KV_Test.log -outputdir common_test_output
+        if [ $failed -eq 0 ]
+        then
+          echo "Bedrock_Build_Azure_Single_KeyVault: Test passed."
+        else
+          echo "Bedrock_Build_Azure_Single_KeyVault: Test failed."
+          exit 1
       env:
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_OBJECT_ID: $(ARM_CLIENT_OBJECT_ID)
@@ -228,7 +242,14 @@ stages:
         export public_key=$(cat id_rsa.pub)
         find $(modulePath)/cluster/environments/azure-multiple-clusters -type f -name '*.tf' -exec sed -i 's/github.com\/Microsoft\/bedrock\/cluster/..\/../g' {} \;
         go test -v -run TestIT_Bedrock_AzureMC_Test -timeout 99999s | tee TestIT_Bedrock_AzureMC_Test.log
+        failed=$?
         terratest_log_parser -testlog TestIT_Bedrock_AzureMC_Test.log -outputdir mc_test_output
+        if [ $failed -eq 0 ]
+        then
+          echo "Bedrock_Build_Azure_Multiple_Clusters: Test passed."
+        else
+          echo "Bedrock_Build_Azure_Multiple_Clusters: Test failed."
+          exit 1
       env:
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_OBJECT_ID: $(ARM_CLIENT_OBJECT_ID)
