add terraform fmt check

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -91,6 +91,18 @@ jobs:
     displayName: 'Install terraform, kubectl, helm'
 
   - script: |
+      terraform fmt -check=true -write=false -list=true > /dev/null
+      if [ $? -eq 0 ]
+      then
+        echo "terraform lint valid."
+      else
+        echo "Invalid lint. Please run terraform fmt."
+        exit 1
+      fi
+    workingDirectory: '$(modulePath)/cluster'
+    displayName: 'Terraform lint check'
+
+  - script: |
       ssh-keygen -f id_rsa -t rsa -N "bedrock@microsoft.com"
       export ssh_key=$(readlink -f id_rsa.pub)
       export public_key=$(cat id_rsa.pub)
